---

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: Deploy a clean /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags:
    - dns
